#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NiftyDialogEffects.Net.Resource", IsApplication=false)]

namespace NiftyDialogEffects.Net
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public static int btn_press_color = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int btn_unpress_color = 2130968581;
			
			// aapt resource value: 0x7f040003
			public static int dialog_bg = 2130968579;
			
			// aapt resource value: 0x7f040001
			public static int divider_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int msg_color = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int text_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int dialog_padding = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int btn_press = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int btn_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int btn_unpress = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int dialog_bg = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public static int alertTitle = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public static int button1 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public static int button2 = 2131165195;
			
			// aapt resource value: 0x7f070007
			public static int contentPanel = 2131165191;
			
			// aapt resource value: 0x7f070009
			public static int customPanel = 2131165193;
			
			// aapt resource value: 0x7f070004
			public static int icon = 2131165188;
			
			// aapt resource value: 0x7f070000
			public static int main = 2131165184;
			
			// aapt resource value: 0x7f070008
			public static int message = 2131165192;
			
			// aapt resource value: 0x7f070001
			public static int parentPanel = 2131165185;
			
			// aapt resource value: 0x7f070006
			public static int titleDivider = 2131165190;
			
			// aapt resource value: 0x7f070003
			public static int title_template = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int topPanel = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int dialog_layout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public static int AppBaseTheme = 2131099652;
			
			// aapt resource value: 0x7f060000
			public static int DialogWindowTitle = 2131099648;
			
			// aapt resource value: 0x7f060003
			public static int dialog_btn = 2131099651;
			
			// aapt resource value: 0x7f060001
			public static int dialog_tran = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int dialog_untran = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
