#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NiftyDialogEffects.Net.Sample.Resource", IsApplication=true)]

namespace NiftyDialogEffects.Net.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NiftyDialogEffects.Net.Resource.Color.btn_press_color = global::NiftyDialogEffects.Net.Sample.Resource.Color.btn_press_color;
			global::NiftyDialogEffects.Net.Resource.Color.btn_unpress_color = global::NiftyDialogEffects.Net.Sample.Resource.Color.btn_unpress_color;
			global::NiftyDialogEffects.Net.Resource.Color.dialog_bg = global::NiftyDialogEffects.Net.Sample.Resource.Color.dialog_bg;
			global::NiftyDialogEffects.Net.Resource.Color.divider_color = global::NiftyDialogEffects.Net.Sample.Resource.Color.divider_color;
			global::NiftyDialogEffects.Net.Resource.Color.msg_color = global::NiftyDialogEffects.Net.Sample.Resource.Color.msg_color;
			global::NiftyDialogEffects.Net.Resource.Color.text_color = global::NiftyDialogEffects.Net.Sample.Resource.Color.text_color;
			global::NiftyDialogEffects.Net.Resource.Dimension.dialog_padding = global::NiftyDialogEffects.Net.Sample.Resource.Dimension.dialog_padding;
			global::NiftyDialogEffects.Net.Resource.Drawable.btn_press = global::NiftyDialogEffects.Net.Sample.Resource.Drawable.btn_press;
			global::NiftyDialogEffects.Net.Resource.Drawable.btn_selector = global::NiftyDialogEffects.Net.Sample.Resource.Drawable.btn_selector;
			global::NiftyDialogEffects.Net.Resource.Drawable.btn_unpress = global::NiftyDialogEffects.Net.Sample.Resource.Drawable.btn_unpress;
			global::NiftyDialogEffects.Net.Resource.Drawable.dialog_bg = global::NiftyDialogEffects.Net.Sample.Resource.Drawable.dialog_bg;
			global::NiftyDialogEffects.Net.Resource.Id.alertTitle = global::NiftyDialogEffects.Net.Sample.Resource.Id.alertTitle;
			global::NiftyDialogEffects.Net.Resource.Id.button1 = global::NiftyDialogEffects.Net.Sample.Resource.Id.button1;
			global::NiftyDialogEffects.Net.Resource.Id.button2 = global::NiftyDialogEffects.Net.Sample.Resource.Id.button2;
			global::NiftyDialogEffects.Net.Resource.Id.contentPanel = global::NiftyDialogEffects.Net.Sample.Resource.Id.contentPanel;
			global::NiftyDialogEffects.Net.Resource.Id.customPanel = global::NiftyDialogEffects.Net.Sample.Resource.Id.customPanel;
			global::NiftyDialogEffects.Net.Resource.Id.icon = global::NiftyDialogEffects.Net.Sample.Resource.Id.icon;
			global::NiftyDialogEffects.Net.Resource.Id.main = global::NiftyDialogEffects.Net.Sample.Resource.Id.main;
			global::NiftyDialogEffects.Net.Resource.Id.message = global::NiftyDialogEffects.Net.Sample.Resource.Id.message;
			global::NiftyDialogEffects.Net.Resource.Id.parentPanel = global::NiftyDialogEffects.Net.Sample.Resource.Id.parentPanel;
			global::NiftyDialogEffects.Net.Resource.Id.titleDivider = global::NiftyDialogEffects.Net.Sample.Resource.Id.titleDivider;
			global::NiftyDialogEffects.Net.Resource.Id.title_template = global::NiftyDialogEffects.Net.Sample.Resource.Id.title_template;
			global::NiftyDialogEffects.Net.Resource.Id.topPanel = global::NiftyDialogEffects.Net.Sample.Resource.Id.topPanel;
			global::NiftyDialogEffects.Net.Resource.Layout.dialog_layout = global::NiftyDialogEffects.Net.Sample.Resource.Layout.dialog_layout;
			global::NiftyDialogEffects.Net.Resource.Style.AppBaseTheme = global::NiftyDialogEffects.Net.Sample.Resource.Style.AppBaseTheme;
			global::NiftyDialogEffects.Net.Resource.Style.DialogWindowTitle = global::NiftyDialogEffects.Net.Sample.Resource.Style.DialogWindowTitle;
			global::NiftyDialogEffects.Net.Resource.Style.dialog_btn = global::NiftyDialogEffects.Net.Sample.Resource.Style.dialog_btn;
			global::NiftyDialogEffects.Net.Resource.Style.dialog_tran = global::NiftyDialogEffects.Net.Sample.Resource.Style.dialog_tran;
			global::NiftyDialogEffects.Net.Resource.Style.dialog_untran = global::NiftyDialogEffects.Net.Sample.Resource.Style.dialog_untran;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int btn_press_color = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int btn_unpress_color = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int dialog_bg = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int divider_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int msg_color = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int text_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int activity_horizontal_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int activity_vertical_margin = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int dialog_padding = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_press = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_unpress = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dialog_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001b
			public const int MyButton = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int action_settings = 2131296284;
			
			// aapt resource value: 0x7f090014
			public const int alertTitle = 2131296276;
			
			// aapt resource value: 0x7f090019
			public const int button1 = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int button2 = 2131296282;
			
			// aapt resource value: 0x7f090016
			public const int contentPanel = 2131296278;
			
			// aapt resource value: 0x7f090018
			public const int customPanel = 2131296280;
			
			// aapt resource value: 0x7f090001
			public const int fadein = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int fall = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int fliph = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int flipv = 2131296267;
			
			// aapt resource value: 0x7f090013
			public const int icon = 2131296275;
			
			// aapt resource value: 0x7f09000f
			public const int main = 2131296271;
			
			// aapt resource value: 0x7f090017
			public const int message = 2131296279;
			
			// aapt resource value: 0x7f090006
			public const int newspager = 2131296262;
			
			// aapt resource value: 0x7f090010
			public const int parentPanel = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int rotatebottom = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int rotateleft = 2131296269;
			
			// aapt resource value: 0x7f090009
			public const int shake = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int sidefall = 2131296264;
			
			// aapt resource value: 0x7f090005
			public const int slideBottom = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int slideleft = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int slideright = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int slidetop = 2131296260;
			
			// aapt resource value: 0x7f09000e
			public const int slit = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int title = 2131296256;
			
			// aapt resource value: 0x7f090015
			public const int titleDivider = 2131296277;
			
			// aapt resource value: 0x7f090012
			public const int title_template = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int topPanel = 2131296273;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int custom_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int action_settings = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int costomview = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int hello_world = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int AppBaseTheme = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int AppTheme = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int DialogWindowTitle = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int dialog_btn = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int dialog_tran = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int dialog_untran = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int my_btn = 2131099654;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
